[package]
name = "r2me"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = { git = "https://github.com/emoon/rust_minifb.git" }